# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14cace6a1c4a439b1cdc8f003d1c58331997ec2cbeb3ac7fd9d2784ec0e2f209f7a4452f2e1272f8dc4e9bb4119abb4d3efc32bbe9cff9c9c319c474583888d4

test:
  secret_key_base: ebff0ce7af97fc35ff78eda43bafee4e0b9b5c3021c6b699d2fad3e3b02445dab4ccc31cbb8db34ecc929488a92812d16555c1ec81dde447beffa53efb9f68e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
